### ISSUE TITLE
New problem with Katex

### ISSUE THREAD

**Issue by pilgrimlyieu** [Jwrede/Anki-KaTeX-Markdown#10]
![1](https://user-images.githubusercontent.com/80107081/125461017-f8054c5e-168d-454d-a882-fbd1c918ed77.png)
![2](https://user-images.githubusercontent.com/80107081/125461023-5ce1c5ce-c25c-4b1b-adb4-fad9123de64a.png)
New Problem Now!
I feel dizzy:(
```markdown
$\begin{cases}\sin\alpha+\sin\beta={{c1::2\sin\dfrac{\alpha+\beta}{2}\cos\dfrac{\alpha-\beta}{2}}}\\\sin\alpha-\sin\beta={{c2::2\cos\dfrac{\alpha+\beta}{2}\sin\dfrac{\alpha-\beta}{2}}}\\\cos\alpha+\cos\beta={{c3::2\cos\dfrac{\alpha+\beta}{2}\cos\dfrac{\alpha-\beta}{2}}}\\\cos\alpha-\cos\beta={{c4::-2\sin\dfrac{\alpha+\beta}{2}\sin\dfrac{\alpha-\beta}{2}}}\end{cases}$
```
Moreover, it works normal in the back side.

**Comment by ficapy** [comment]
It' s normal in my case

**Comment by Jwrede** [comment]
```
$\begin{cases}\sin\alpha+\sin\beta={{c1::2\sin\dfrac{\alpha+\beta}{2}\cos\dfrac{\alpha-\beta}{2} }}\\\sin\alpha-\sin\beta={{c2::2\cos\dfrac{\alpha+\beta}{2}\sin\dfrac{\alpha-\beta}{2} }}\\\cos\alpha+\cos\beta={{c3::2\cos\dfrac{\alpha+\beta}{2}\cos\dfrac{\alpha-\beta}{2} }}\\\cos\alpha-\cos\beta={{c4::-2\sin\dfrac{\alpha+\beta}{2}\sin\dfrac{\alpha-\beta}{2} }}\end{cases}$
```
this works, if you have `}}}` in a cloze it'll interpret the first two `}`'s as the end of the cloze so you'll have to type `} }}`

**Comment by pilgrimlyieu** [comment]
> 
> this works, if you have `}}}` in a cloze it'll interpret the first two `}`'s as the end of the cloze so you'll have to type `} }}`
Thanks you very much! It works! 
Thanks you very much. It works !
