### ISSUE TITLE
Can I add macros for Katex?

### ISSUE THREAD

**Issue by pilgrimlyieu** [Jwrede/Anki-KaTeX-Markdown#11]
Sometimes the command is too long. So if it's possible to add macros for Katex?

**Comment by Jwrede** [comment]
There was another issue with that question already: https://github.com/Jwrede/Anki-KaTeX-Markdown/issues/6 sadly I wasn't able to implement the plain text file because it doesn't work with ankiDroid or ankiweb

**Comment by pilgrimlyieu** [comment]
> There was another issue with that question already: #6 sadly I wasn't able to implement the plain text file because it doesn't work with ankiDroid or ankiweb

Such A Wonderful Magic! It works not only on Anki but also on AnkiDroid and AnkiWeb!
