### ISSUE TITLE
The function "\pu" sometimes doesn't work.

### ISSUE THREAD

**Issue by pilgrimlyieu** [Jwrede/Anki-KaTeX-Markdown#12]
![2021-08-10_19-42-00](https://user-images.githubusercontent.com/80107081/128861279-94b759a2-f8f0-40e4-b5c8-948e6d3f5660.png)

KaTeX supports the function. However, it works unstably in Anki.

![动画](https://user-images.githubusercontent.com/80107081/128861632-98d1a127-95eb-4008-a54f-ac2e63174d01.gif)

![9A64F257D86B800C6904441C88CFB363](https://user-images.githubusercontent.com/80107081/128861887-056cbd54-3162-4c93-8528-ca7e6ecc7424.jpg)

And it DOESN'T work in AnkiDroid.

Can it be solved? Appreciatly.

>The code is `$$\pu{m/s}$$`.

**Comment by Jwrede** [comment]
mhm that's truly weird, does the `\ce` function work for you?

**Comment by pilgrimlyieu** [comment]
> mhm that's truly weird, does the `\ce` function work for you?

No. And I remembered that you've fixed it before. Really weird.

**Comment by Jwrede** [comment]
I don't remember changing anything in the ast two weeks, sadly I'm on vacation right now so I can't fix it until sunday. I just checked on my phone and it doesn't work either, maybe I deleted something important last update, sorry for the inconvenience!

**Comment by pilgrimlyieu** [comment]
> I don't remember changing anything in the ast two weeks, sadly I'm on vacation right now so I can't fix it until sunday. I just checked on my phone and it doesn't work either, maybe I deleted something important last update, sorry for the inconvenience!

It doesn't matter. I can wait. Enjoy your vacation!:smile:

**Comment by Jwrede** [comment]
thanks alot!

**Comment by Jwrede** [comment]
I accidently reverted too many changes with git after trying to make the cloze stylable, Chemistry support should work again now

**Comment by pilgrimlyieu** [comment]
> I accidently reverted too many changes with git after trying to make the cloze stylable, Chemistry support should work again now

Extremely thank you! It works now.

**Comment by pilgrimlyieu** [comment]
> I accidently reverted too many changes with git after trying to make the cloze stylable, Chemistry support should work again now

Extremely thank you! It works now.
