### ISSUE TITLE
Cannot  get the realtime output as i type something.

### ISSUE THREAD

**Issue by LiuZ0814** [Jwrede/Anki-KaTeX-Markdown#13]
It is a great addon but I got this [problem](https://i.imgur.com/gbiW7Sp.png) that i cannot get the realtime output as i am typing something. A lot of codes just show below.
There is no setting page in the addon setting and I cannot understand javascript nor css.So I cannot figure it out.

**Comment by pilgrimlyieu** [comment]
![2021-08-14_20-43-11](https://user-images.githubusercontent.com/80107081/129446697-f958e8ec-6057-48db-bab1-76ca2bd5c6b8.png)

It works normal in my case. Have you changed something?

**Comment by pilgrimlyieu** [comment]
You can use <kbd>Ctrl+Shift+X</kbd>to check the original code.

**Comment by LiuZ0814** [comment]
When i switch to a local account and use this template，it works ！So I guess maybe there is one addon conflict with it，I will
check them one by one.

**Comment by Jwrede** [comment]
If you found it please tell me, I'll see if I can fix it

**Comment by LiuZ0814** [comment]
Hi,Jwrede.I fixed it by disabling the addon 1972239816(Syntax Highlighting FORK (night mode fix, gui config, etc.) )and then by restarting anki this problem got fixed.Now I tried its alternative addon 1463041493(Syntax Highlighting for Code).To my surprise,they are compatible.So you could set a notice that this addon is conflict with 1972239816.Thanks for your reply.

**Comment by Jwrede** [comment]
Okay thanks alot, I'll add a notice. This addon also has Syntax Highlighting in code blocks if you didn't know yet, just type:
```
(Triple backtick) python
...
(Triple backtick)
```
for python syntax highlighting
