### ISSUE TITLE
I'd like to know Is there any way to auto-generate catalogue like typora "[toc]" function in Anki-KaTeX-Markdown?

### ISSUE THREAD

**Issue by skywoodlin** [Jwrede/Anki-KaTeX-Markdown#14]

**Comment by Jwrede** [comment]
Can you give me an example video or a gif that explains the functionality and how you intend to use it in Anki? 
I haven't heard of `[toc]` yet but I've seen plug-ins for markdown-it, which I use for this Add-on, which implement toc but I'm not sure exactly what it is or how it works, so it's theoretically possible
