### ISSUE TITLE
While a field is empty, after fields don't work.

### ISSUE THREAD

**Issue by pilgrimlyieu** [Jwrede/Anki-KaTeX-Markdown#17]
Hello, here is a problem trouble me for a long time.

I exceptionally appreciate your great works. However, I have more than two fields that need to support KaTeX and Markdown. So I equip my template with your codes.

I add html id such as `back1` and `back2` to the extra field like this.

![2021-09-05_18-01-06](https://user-images.githubusercontent.com/80107081/132122855-bc9edb13-c25c-4c98-b367-73f7e8dc6fbd.png)

![2021-09-05_17-59-46](https://user-images.githubusercontent.com/80107081/132122829-1f3a30b6-2561-400c-85f6-fb1a0a9b6186.png)

It works great like this.

![2021-09-05_17-55-32](https://user-images.githubusercontent.com/80107081/132122839-b37cd2e2-4bc1-4993-90bf-4f54843b47d8.png)

![2021-09-05_17-55-41](https://user-images.githubusercontent.com/80107081/132122840-6f7b1508-a91e-4117-991e-90177986557a.png)

However, when the second field I call `答案` is empty, after fields will not work.

![2021-09-05_18-03-45](https://user-images.githubusercontent.com/80107081/132122950-17e8f287-9ac8-49a3-9320-bc1c6fc5e4d2.png)

![2021-09-05_18-03-52](https://user-images.githubusercontent.com/80107081/132122936-b27a0fcc-dd71-482a-bfe0-b1daad18f4c0.png)

I suppose it as the problem of `render` function's order. The `render` function renders `front` id, `back` id etc. in turn. And when the `back` id that stands for the second field is empty, this will break, which cause rest fields don't work.

![2021-09-05_18-12-01](https://user-images.githubusercontent.com/80107081/132123120-9a4a48c6-505b-4cf9-aa5c-c57c7869da6c.png)

So can you tell me how to solve it? I will really appreciate it!

**Comment by Jwrede** [comment]
Mhm I've tried to implement a minimal example of your card like this:

### Front:
```javascript


<div id="front"><pre>{{Front}}</pre></div>

<script>
	var getResources = [
		getCSS("_katex.css", "https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css"),
		getCSS("_highlight.css", "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.0.1/styles/default.min.css"),
		getScript("_highlight.js", "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.0.1/highlight.min.js"),
		getScript("_katex.min.js", "https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js"),
		getScript("_auto-render.js", "https://cdn.jsdelivr.net/gh/Jwrede/Anki-KaTeX-Markdown/auto-render-cdn.js"),
		getScript("_markdown-it.min.js", "https://cdnjs.cloudflare.com/ajax/libs/markdown-it/12.0.4/markdown-it.min.js"),
                getScript("_markdown-it-mark.js","https://cdn.jsdelivr.net/gh/Jwrede/Anki-KaTeX-Markdown/_markdown-it-mark.js")
	];
        Promise.all(getResources).then(() => getScript("_mhchem.js", "https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/contrib/mhchem.min.js")).then(render).catch(show);
	

	function getScript(path, altURL) {
		return new Promise((resolve, reject) => {
			let script = document.createElement("script");
			script.onload = resolve;
			script.onerror = function() {
				let script_online = document.createElement("script");
				script_online.onload = resolve;
				script_online.onerror = reject;
				script_online.src = altURL;
				document.head.appendChild(script_online);
			}
			script.src = path;
			document.head.appendChild(script);
		})
	}

	function getCSS(path, altURL) {
		return new Promise((resolve, reject) => {
			var css = document.createElement('link');
			css.setAttribute('rel', 'stylesheet');
			css.type = 'text/css';
			css.onload = resolve;
			css.onerror = function() {
				var css_online = document.createElement('link');
				css_online.setAttribute('rel', 'stylesheet');
				css_online.type = 'text/css';
				css_online.onload = resolve;
				css.onerror = reject;
				css_online.href = altURL;
				document.head.appendChild(css_online);
			}
			css.href = path;
			document.head.appendChild(css);
		});
	}


	function render() {
		renderMath("front");
		markdown("front");
		show();
	}

	function show() {
		document.getElementById("front").style.visibility = "visible";
	}

	function renderMath(ID) {
		let text = document.getElementById(ID).innerHTML;
		text = replaceInString(text);
		document.getElementById(ID).textContent = text;
		renderMathInElement(document.getElementById(ID), {
			delimiters:  [
  				{left: "$$", right: "$$", display: true},
  				{left: "$", right: "$", display: false}
			],
            throwOnError : false
		});
	}

	function markdown(ID) {
		let md = new markdownit({typographer: true, html:true, highlight: function (str, lang) {
                            if (lang && hljs.getLanguage(lang)) {
                                try {
                                    return hljs.highlight(str, { language: lang }).value;
                                } catch (__) {}
                            }

                            return ''; // use external default escaping
                        }}).use(markdownItMark);
		let text = replaceHTMLElementsInString(document.getElementById(ID).innerHTML);
		text = md.render(text);
		document.getElementById(ID).innerHTML = text.replace(/&lt;\/span&gt;/gi,"\\");
	}
	function replaceInString(str) {
		str = str.replace(/<[\/]?pre[^>]*>/gi, "");
		str = str.replace(/<br\s*[\/]?[^>]*>/gi, "\n");
		str = str.replace(/<div[^>]*>/gi, "\n");
		// Thanks Graham A!
		str = str.replace(/<[\/]?span[^>]*>/gi, "")
		str.replace(/<\/div[^>]*>/g, "\n");
		return replaceHTMLElementsInString(str);
	}

	function replaceHTMLElementsInString(str) {
		str = str.replace(/&nbsp;/gi, " ");
		str = str.replace(/&tab;/gi, "	");
		str = str.replace(/&gt;/gi, ">");
		str = str.replace(/&lt;/gi, "<");
		return str.replace(/&amp;/gi, "&");
	}
</script>
```

### Back
```javascript


<div id="front"><pre>{{Front}}</pre></div>

<hr id=answer>

<div id="back"><pre>{{Back}}</pre></div>
<div id="back1"><pre>{{Back1}}</pre></div>
<div id="back2"><pre>{{Back2}}</pre></div>

<script>
	var getResources = [
		getCSS("_katex.css", "https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css"),
		getCSS("_highlight.css", "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.0.1/styles/default.min.css"),
		getScript("_highlight.js", "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.0.1/highlight.min.js"),
		getScript("_katex.min.js", "https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js"),
		getScript("_auto-render.js", "https://cdn.jsdelivr.net/gh/Jwrede/Anki-KaTeX-Markdown/auto-render-cdn.js"),
		getScript("_markdown-it.min.js", "https://cdnjs.cloudflare.com/ajax/libs/markdown-it/12.0.4/markdown-it.min.js"),
		getScript("_markdown-it-mark.js","https://cdn.jsdelivr.net/gh/Jwrede/Anki-KaTeX-Markdown/_markdown-it-mark.js")
	];
        Promise.all(getResources).then(() => getScript("_mhchem.js", "https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/contrib/mhchem.min.js")).then(render).catch(show);
	

	function getScript(path, altURL) {
		return new Promise((resolve, reject) => {
			let script = document.createElement("script");
			script.onload = resolve;
			script.onerror = function() {
				let script_online = document.createElement("script");
				script_online.onload = resolve;
				script_online.onerror = reject;
				script_online.src = altURL;
				document.head.appendChild(script_online);
			}
			script.src = path;
			document.head.appendChild(script);
		})
	}

	function getCSS(path, altURL) {
		return new Promise((resolve, reject) => {
			var css = document.createElement('link');
			css.setAttribute('rel', 'stylesheet');
			css.type = 'text/css';
			css.onload = resolve;
			css.onerror = function() {
				var css_online = document.createElement('link');
				css_online.setAttribute('rel', 'stylesheet');
				css_online.type = 'text/css';
				css_online.onload = resolve;
				css_online.onerror = reject;
				css_online.href = altURL;
				document.head.appendChild(css_online);
			}
			css.href = path;
			document.head.appendChild(css);
		});
	}

	function render() {
		renderMath("front");
		markdown("front");
		renderMath("back");
		markdown("back");
		renderMath("back1");
		markdown("back1");
		renderMath("back2");
		markdown("back2");
		show();
	}

	function show() {
		document.getElementById("front").style.visibility = "visible";
		document.getElementById("back").style.visibility = "visible";
	}


	function renderMath(ID) {
		let text = document.getElementById(ID).innerHTML;
		text = replaceInString(text);
		document.getElementById(ID).textContent = text;
		renderMathInElement(document.getElementById(ID), {
			delimiters:  [
  				{left: "$$", right: "$$", display: true},
  				{left: "$", right: "$", display: false}
			],
                        throwOnError : false
		});
	}
	function markdown(ID) {
		let md = new markdownit({typographer: true, html:true, highlight: function (str, lang) {
                            if (lang && hljs.getLanguage(lang)) {
                                try {
                                    return hljs.highlight(str, { language: lang }).value;
                                } catch (__) {}
                            }

                            return ''; // use external default escaping
                        }}).use(markdownItMark);
		let text = replaceHTMLElementsInString(document.getElementById(ID).innerHTML);
		text = md.render(text);
		document.getElementById(ID).innerHTML = text.replace(/&lt;\/span&gt;/gi,"\\");
	}
	function replaceInString(str) {
		str = str.replace(/<[\/]?pre[^>]*>/gi, "");
		str = str.replace(/<br\s*[\/]?[^>]*>/gi, "\n");
		str = str.replace(/<div[^>]*>/gi, "\n");
		// Thanks Graham A!
		str = str.replace(/<[\/]?span[^>]*>/gi, "")
		str.replace(/<\/div[^>]*>/g, "\n");
		return replaceHTMLElementsInString(str);
	}

	function replaceHTMLElementsInString(str) {
		str = str.replace(/&nbsp;/gi, " ");
		str = str.replace(/&tab;/gi, "	");
		str = str.replace(/&gt;/gi, ">");
		str = str.replace(/&lt;/gi, "<");
		return str.replace(/&amp;/gi, "&");
	}
</script>
```

and it seems to work fine:
![image](https://user-images.githubusercontent.com/62910358/132138470-b312ece0-3db5-4275-996c-fd63bdf92dbc.png)
rendered:
![image](https://user-images.githubusercontent.com/62910358/132138484-1d92ab4e-7e9a-4b51-8683-cc0d9e71b0ae.png)

Please tell me if I forgot something, it seems to me it may be because of the other CSS, JS you added, you can install the Anki Addon **AnkiWebView Inspector**, then right click on the rendered card then choose **inspect**:
![image](https://user-images.githubusercontent.com/62910358/132138553-6c96be8a-08db-49f1-ae96-1f9764fb5ee4.png)
Then you can see if you get any errors while rendering, please tell me if you get an error or if there is no error then its easier for me to help, thanks!

**Comment by pilgrimlyieu** [comment]
Sorry to reply you so late because I was in the school this whole week.

I've copied your showed code and it works. However, when I deleted all CSS styles, it  still didn't work.

According to your recommendation, I installed the add-on. But I have no idea with it. So if I didn't guess wrong, you may want this? If I misunderstand you, please tell me!

![2021-09-10_17-29-35](https://user-images.githubusercontent.com/80107081/132833614-6b6fdb3e-5f9c-4013-8575-04024a834818.png)

This is my card package.

[Card.zip](https://github.com/Jwrede/Anki-KaTeX-Markdown/files/7142851/Card.zip)

**Comment by pilgrimlyieu** [comment]
I think I've found where the reason lie.

When I delete the outside fields(maybe) which wrapped the second field(I call it `答案` and you call it `Back`), It works.

![2021-09-10_17-43-57](https://user-images.githubusercontent.com/80107081/132834988-3e78f229-5b72-44d5-8ad5-b069417636be.png)

However, the wrappings are used to check if the field is empty and if so hide it. When I delete it, it has a side-effect. So can you tell me a replaced solution? Thanks you very much!

**Comment by pilgrimlyieu** [comment]
My card has a slide effect and when I delete the wrappings, it seem the second field as a empty line and cause showing a short left border when I turn over the card.

**Comment by pilgrimlyieu** [comment]
Also, when there is many subscripts in math mode, it'll mistakenly consider the `_` as a part of italic font. And the result is

![2021-09-10_18-16-12](https://user-images.githubusercontent.com/80107081/132838918-cda1ffa5-d620-48b2-bd62-f5c8b6261b9e.png)

Can you tell me how to change the token stand for italic font? I always use `*` instead  of  `_` so I want to just remain `*`.

**Comment by pilgrimlyieu** [comment]
> Also, when there is many subscripts in math mode, it'll mistakenly consider the `_` as a part of italic font. And the result is
> 
> ![2021-09-10_18-16-12](https://user-images.githubusercontent.com/80107081/132838918-cda1ffa5-d620-48b2-bd62-f5c8b6261b9e.png)
> 
> Can you tell me how to change the token stand for italic font? I always use `*` instead of `_` so I want to just remain `*`.
> 
> ```gfm
> 若将总体分$k$层，第$j$层抽取的样本为$x_{j1},x_{j2},\cdots,x_{jn_j}$，第$j$层样本容量为$n_j$，样本均值为$\overline{x}_j$，样本方差为$s_j^2$。则全部样本样本容量$n=\displaystyle\sum^k_{j=1}n_j$，样本均值$\overline{x}=\dfrac{1}{n}\displaystyle\sum^k_{j=1}n _ j\overline{x}_j$，样本方差$s^2=\dfrac{1}{n}\displaystyle\sum^k_{j=1}n_j[s_j^2+(\overline{x}_j-\overline{x})^2]$
> ```

Though, the italic sum symbol is quite interesting lol :smile:

**Comment by pilgrimlyieu** [comment]
Also, there is no space between numbers and letters in `pu` environment like

```markdown
$\pu{1mol/L}$
```

However, it should have.

**Comment by Jwrede** [comment]
Both last problems are things that bug me as well, these bugs are in this addon for a long time now but I wasn't able to fix them yet, I'll probably have to do a major rework for that which will probably make the implementation alot cleaner as well. Sadly my time is really limited right now because of uni and work at the same time especially next week, that's why I didn't answer until now as well.
These changes could potentially fix the error you have with your custom cards but I'm not sure yet.
I'll take one day off the week starting on the 27. or the following week to do this so please be patient, I hope I'll catch both errors, sorry it's taking so long!

**Comment by pilgrimlyieu** [comment]
That's no problem. Thanks for your great work!

**Comment by proItheus** [comment]
> Also, when there is many subscripts in math mode, it'll mistakenly consider the `_` as a part of italic font. And the result is
> 
> ![2021-09-10_18-16-12](https://user-images.githubusercontent.com/80107081/132838918-cda1ffa5-d620-48b2-bd62-f5c8b6261b9e.png)
> 
> Can you tell me how to change the token stand for italic font? I always use `*` instead of `_` so I want to just remain `*`.
> 
> ```gfm
> 若将总体分$k$层，第$j$层抽取的样本为$x_{j1},x_{j2},\cdots,x_{jn_j}$，第$j$层样本容量为$n_j$，样本均值为$\overline{x}_j$，样本方差为$s_j^2$。则全部样本样本容量$n=\displaystyle\sum^k_{j=1}n_j$，样本均值$\overline{x}=\dfrac{1}{n}\displaystyle\sum^k_{j=1}n _ j\overline{x}_j$，样本方差$s^2=\dfrac{1}{n}\displaystyle\sum^k_{j=1}n_j[s_j^2+(\overline{x}_j-\overline{x})^2]$
> ```

You can try a quick fix by adding
```javascript
 text=text.replace(/_/g,"");
```
before `text = md.render(text);` in definition of function markdown(). This will delete "_" in the text before rendering it using markdown. Tested with your text and works normally.

**Comment by proItheus** [comment]
> I think I've found where the reason lie.
> 
> When I delete the outside fields(maybe) which wrapped the second field(I call it `答案` and you call it `Back`), It works.
> 
> ![2021-09-10_17-43-57](https://user-images.githubusercontent.com/80107081/132834988-3e78f229-5b72-44d5-8ad5-b069417636be.png)
> 
> However, the wrappings are used to check if the field is empty and if so hide it. When I delete it, it has a side-effect. So can you tell me a replaced solution? Thanks you very much!

Moving the wrappings inside the html tag solves this for me. 
```html
{{#Front}}<div id=front><pre>something</pre></div>{{/Front}}
```
will be changed to 
```html
<div id=front><pre>{{#Front}}something{{/Front}}</pre></div>

**Comment by pilgrimlyieu** [comment]
Extremely thankful to @proItheus! All your methods work perfectly!
