### ISSUE TITLE
Markdown code centered in AnkiMobile

### ISSUE THREAD

**Issue by nadavc** [Jwrede/Anki-KaTeX-Markdown#19]
Thank you for your excellent plugin! It's been immensely helpful.

When viewing code on AnkiMobile, code seems to be aligned to center. Could we have it be aligned to the left, like it is on the desktop?

![PNG image](https://user-images.githubusercontent.com/610392/140694850-8ebf7ab7-72f9-4470-9a23-70e26cf62d8d.png)

**Comment by pilgrimlyieu** [comment]
I don't use AnkiMobile. But I think you can try to add the following code to the `Styling`.

```css
.card {
  text-align:left
}
```

**Comment by Jwrede** [comment]
I'm sorry for being so inactive lately, I've been busier than expected. I can't replicate this problem on my ankidroid, the text is left aligned there but I tried fixing your problem with the latest update. 
Sorry for everyone reading this who asked for something in the other issues, right now I can't really find the time to do a big update but maybe in the future

**Comment by Jwrede** [comment]
Closed because of inactivity
