### ISSUE TITLE
Version v1.2 does not render.

### ISSUE THREAD

**Issue by huandney** [Jwrede/Anki-KaTeX-Markdown#2]
First, thanks for the addon.
**in version 1.0, sometimes the rendering worked, sometimes not, as below:**
![Error](https://user-images.githubusercontent.com/19948348/111364794-114e5880-8668-11eb-8fef-b6cdf74f8bf0.gif)
**In version 1.2, rendering does not work at all**
![error2](https://user-images.githubusercontent.com/19948348/111364832-1c08ed80-8668-11eb-9013-217a47bda08e.gif)

**Comment by Jwrede** [comment]
then I broke something with the new newest update, give me a minute, sorry!

**Comment by huandney** [comment]
Just a detail, on ankidroid it seems to work well!

**Comment by Jwrede** [comment]
I think I solved it with that detail, can you try it out and tell me how it went?
Thanks for the patience!

**Comment by huandney** [comment]
It seems to be working perfectly, thank you very much!

**Comment by Jwrede** [comment]
Perfect!
