### ISSUE TITLE
How to create cloze inside the equation

### ISSUE THREAD

**Issue by Gez0377** [Jwrede/Anki-KaTeX-Markdown#26]
For example, I want to create 
```markdown
$$
\frac{1}{ {{c1::2}} }=0.5
$$
```
And want it to be displayed as 

![image](https://user-images.githubusercontent.com/33337630/150649795-36351c35-ab33-4650-ae79-2388daaa93c0.png)

How to do it by this plugin.

**Comment by pilgrimlyieu** [comment]
It works normal, doesn't it?

**Comment by Gez0377** [comment]
> It works normal, doesn't it?

I tried it again. It works normal. 

I thought there was some problem because in the preview area it would display:

![image](https://user-images.githubusercontent.com/33337630/151708188-79041ccc-31c8-4cf8-ad16-c511fcb8dd0b.png)

**Comment by pilgrimlyieu** [comment]
> > It works normal, doesn't it?
> 
> I tried it again. It works normal.
> 
> I thought there was some problem because in the preview area it would display:
> 
> ![image](https://user-images.githubusercontent.com/33337630/151708188-79041ccc-31c8-4cf8-ad16-c511fcb8dd0b.png)

Because the preview area can't recognize the cloze. The preview area just shows the actual result of the markdown code regardless of the cloze effect in Anki.
