### ISSUE TITLE
Extraneous non-working HTML tags in a code block

### ISSUE THREAD

**Issue by evgeek** [Jwrede/Anki-KaTeX-Markdown#27]
Thanks for the great extension! I have a question about the `code` block: how to remove html tags?
![image](https://user-images.githubusercontent.com/93479789/153052581-ea052dd9-f645-4e03-b904-b6b8328db507.png)

**Comment by evgeek** [comment]
I realized that the problem is the dollar sign. You can escape it with a backslash, but how to remove the backslash from the result?
![image](https://user-images.githubusercontent.com/93479789/153054324-9f4beab0-cd3a-4010-b85e-e101db0791fa.png)

**Comment by ficapy** [comment]
https://docs.microsoft.com/en-us/windows/win32/dataxchg/clipboard-formats

My guess is that this is the cause of the problem, You might try creating a new card and enter it manually, without copying

**Comment by evgeek** [comment]
Alas, it didn't help. I think this is due to a conflict with the KaTeX syntax.
> Access KaTeX by $...$ for inline math or $$...$$ for displaystyle math, a list of supported functions can be found [here](https://katex.org/docs/supported.html)

**Comment by ficapy** [comment]
@evgeek  oh, got it,  because there are multiple $ .....

**Comment by pilgrimlyieu** [comment]
Maybe you can push <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>X</kbd> to open the HTML editor to check if there has some HTML tags.

**Comment by evgeek** [comment]
@pilgrimlyieu Didn't know about this hotkey! :)
But it doesn't work either

![image](https://user-images.githubusercontent.com/93479789/153848967-eee7bc90-8ea5-4784-a598-f7324fc3540b.png)

**Comment by pilgrimlyieu** [comment]
> @pilgrimlyieu Didn't know about this hotkey! :) But it doesn't work either
> 
> ![image](https://user-images.githubusercontent.com/93479789/153848967-eee7bc90-8ea5-4784-a598-f7324fc3540b.png)

[This issue](https://github.com/Jwrede/Anki-KaTeX-Markdown/issues/24) may help you. :smile:

**Comment by pilgrimlyieu** [comment]
Actually, the preview zone can be added by modifying something if you need it a lot.

First, open the file `__init__.py` in folder `addons21\1087328706` and find

```python
def markdownPreview(editor):
    if editor.note.model()["name"] in [MODEL_NAME + " Basic", MODEL_NAME + " Cloze"]:
        editor.web.eval(HTMLforEditor)
        editor.web.eval("""
            var style = document.createElement('style');
            style.type = 'text/css';
            style.innerText = `
                table, th, td {
                    border: 1px solid black;
                    border-collapse: collapse;
                }
                pre code {
                    background-color: #eee;
                    border: 1px solid #999;
                    display: block;
                    padding: 20px;
                    overflow: auto;
                }`;
            document.head.appendChild(style);
        """)
    else:
        editor.web.eval("""
					var area = document.getElementById('markdown-area');
					if(area) area.remove();
        """)
```

you can add the name of your template in `[MODEL_NAME + " Basic", MODEL_NAME + " Cloze"]` like `[MODEL_NAME + " Basic", MODEL_NAME + " Cloze", "MyTemplate"]`

However, if your template has more than two fields, you may need extra preview zone.

You can open `HTMLandCSS.py` and find

```javascript
        keyupFunc = function() {
            var text = '# Field 1\\n' + fields[0].children[1].shadowRoot.children[2].innerHTML;
            text += "\\n# Field 2\\n" + fields[1].children[1].shadowRoot.children[2].innerHTML;
            render(text);
        }
```

Then follow the law and add like

```javascript
        keyupFunc = function() {
            var text = '# Field 1\\n' + fields[0].children[1].shadowRoot.children[2].innerHTML;
            text += "\\n# Field 2\\n" + fields[1].children[1].shadowRoot.children[2].innerHTML;
            text += "\\n# Field 3\\n" + fields[2].children[1].shadowRoot.children[2].innerHTML;
            render(text);
        }
```

But the change will be cover if the addon updates. So you have to backup this two files if you still need the function.

**Comment by evgeek** [comment]
This works too! Thanks :)

> First, open the file __init__.py in folder addons21\1087328706

Full path for me - `C:\Users\%USERS%\AppData\Roaming\Anki2\addons21\1087328706`
