### ISSUE TITLE
Place decompressed files in the repo

### ISSUE THREAD

**Issue by proItheus** [Jwrede/Anki-KaTeX-Markdown#32]
Currently, except for some js, this addon's codes lie in a ".ankiaddon" compressed file. I think it's better to have them directly in the repo and left the compressed file in places such as releases, as [awsomeTTS](https://github.com/AwesomeTTS/awesometts-anki-addon) does. Or use ci to automatically generate it. This will make the git log a lot more readable and easier to contribute to the code.

**Comment by Jwrede** [comment]
I think I've managed to do this, can you confirm it?

**Comment by proItheus** [comment]
Yeah I can see the files now. But maybe it's better to use some version number as release name? Thanks for your effort!

**Comment by Jwrede** [comment]
Yea makes sense, did that. Just open this issue again if I missed something
