### ISSUE TITLE
"\\" in Katex parsed wrongly?

### ISSUE THREAD

**Issue by icearchimage** [Jwrede/Anki-KaTeX-Markdown#4]
If the code of a Math expression containing a `\\` symbol, it does not render. 
I noticed the `\\` becoming a line break.
![image](https://user-images.githubusercontent.com/18141546/111415301-9004cd80-871c-11eb-84c1-c803a0d3865d.png)

If the `\\` is removed, it works fine.
![image](https://user-images.githubusercontent.com/18141546/111415244-78c5e000-871c-11eb-8d8b-92831f1fe71a.png)

**Comment by Jwrede** [comment]
The reason why there are so many parsing problems like this one is that Anki modifies the text fields quite heavily and I have to predict all of them, thats why you'll probably see some more of them, thats why I appreciate every single problem you find :D

I think i fixed it in the latest version, please let me know if it works for you now!

**Comment by icearchimage** [comment]
It works now, thanks!

**Comment by Jwrede** [comment]
Please make sure to update again if you get a few problems right now, I uploaded a falsy update 1 or 2 hours ago, should work again now!
