### ISSUE TITLE
Issue with formatting of C++ templated code

### ISSUE THREAD

**Issue by PuneetMatharu** [Jwrede/Anki-KaTeX-Markdown#7]
Hi, thanks for the excellent add-on. However, I have a problem when trying to render the following C++ code in a code block:
```cpp
a<b, c> m;
```
The code unexpectedly gets translated into the following on-screen code:
```cpp
a<b, c=""> m;
```
and `</b,>` is added to the end of the text after the code block. Do you happen to know how to fix this? Thanks!

**Comment by Jwrede** [comment]
Anki really doesn't make it easy for me to clean all the text from HTML symbols, the problem you're talking about probably arises from Anki thinking your `a<b, c>` is an HTML tag.
I think I managed to fix it for now, please tell me if it works now and also please tell me everytime you find a bug!
Thanks for the report

**Comment by PuneetMatharu** [comment]
That works a treat, thanks!

**Comment by Jwrede** [comment]
glad to hear that!
