### ISSUE TITLE
Is it possible to live preview while editing?

### ISSUE THREAD

**Issue by ficapy** [Jwrede/Anki-KaTeX-Markdown#8]
Very wonderful markdown plugin, please ask if there is a way to implement the left edit, the right side of the live display rendering results, this is more interactive!

**Comment by Jwrede** [comment]
As far as I know it's only possible to use Javascript when the card itself is rendering, while typing there probably is no way to render markdown in an extra field, maybe there is a way to implement it but I'd probably have to reverse engineer the source code for that. For now if you didn't know there is a `Cards...` button on the left upper side while adding a new card where you can see how your card will be rendered, I hope that helps

**Comment by ficapy** [comment]
[https://github.com/ssricardo/anki-plugins/blob/master/anki-markdown/README.md](https://github.com/ssricardo/anki-plugins/blob/master/anki-markdown/README.md)
I found this markdown plugin with a preview function, I'll see how it is implemented first

**Comment by Jwrede** [comment]
Just rendering it in a text field below would probably be possible, I'll see what i can do later this day, thanks for the suggestion!

**Comment by Jwrede** [comment]
Okay I think I might have found a way to implement this, this'll probably take me a little bit of time but I'll keep you updated

**Comment by Jwrede** [comment]
![image](https://user-images.githubusercontent.com/62910358/124817703-6c36f300-df6a-11eb-867e-6217ae6bb3b0.png)
This is my current progress, tell me if you got any ideas on how to improve it, it'll probably take a few days until I'm ready because I'll be busy for a few days

**Comment by Jwrede** [comment]
![](https://s6.gifyu.com/images/ezgif-3-fabcb4d8066a.gif)
This is my current progress, tell me if you got any ideas on how to improve it, it'll probably take a few days until I'm ready because I'll be busy for a few days

**Comment by ficapy** [comment]
I think this is great and has basically implemented the live preview requirement. You could release a new version and wait for feedback from other users.  Thanks for your work again.

**Comment by Jwrede** [comment]
Yea I'll release it soon, just making sure there are no bugs that could affect the other parts of the add-on

**Comment by Jwrede** [comment]
Previewer is online, please tell me if it works

**Comment by ficapy** [comment]
> Previewer is online, please tell me if it works

Yeah, It works great~~
