### ISSUE TITLE
Issue about Katex

### ISSUE THREAD

**Issue by pilgrimlyieu** [Jwrede/Anki-KaTeX-Markdown#9]
![1](https://user-images.githubusercontent.com/80107081/125448789-83366162-6ed3-4447-80f7-d2035a2debd7.png)
![2](https://user-images.githubusercontent.com/80107081/125448801-bd359988-2df9-4b74-a125-2fb973daffea.png)
What's wrong with it? 
I have OCD. 😂
Please rescue me! 
The mathrm font doesn't work.
```markdown
$\begin{cases}\sin\alpha\sin\beta=\dfrac{1}{2}[\sin(\alpha+\beta)+\sin(\alpha-\beta)]\\\sin\alpha\cos\beta=-\dfrac{1}{2}[\cos(\alpha+\beta)-\cos(\alpha-\beta)]\\\cos\alpha\cos\beta=\dfrac{1}{2}[\cos(\alpha+\beta)+\cos(\alpha-\beta)]\end{cases}$
```

>The problem doesn't happen in AnkiDroid so it would not trouble me😂.

**Comment by ficapy** [comment]
> ![1](https://user-images.githubusercontent.com/80107081/125448789-83366162-6ed3-4447-80f7-d2035a2debd7.png)
> ![2](https://user-images.githubusercontent.com/80107081/125448801-bd359988-2df9-4b74-a125-2fb973daffea.png)
> What's wrong with it?
> I have OCD. 😂
> Please rescue me!
> The mathrm font doesn't work.

Maybe you should give the original input instead of only screenshots, it would be easier to identify the problem

**Comment by pilgrimlyieu** [comment]
> > What's wrong with it?
> > I have OCD. 😂
> > Please rescue me!
> > The mathrm font doesn't work.
> 
> Maybe you should give the original input instead of only screenshots, it would be easier to identify the problem

Thanks you for reminding me!

**Comment by Jwrede** [comment]
I think this has to do with the syntax highlighting you're using in the program you are copying the input from, Anki pastes not only the text but the syntax highlighting as well, can you copy the text as it is in anki into a comment here?

**Comment by pilgrimlyieu** [comment]
> I think this has to do with the syntax highlighting you're using in the program you are copying the input from, Anki pastes not only the text but the syntax highlighting as well, can you copy the text as it is in anki into a comment here?

```markdown
$\begin{cases}\sin\alpha\sin\beta=\dfrac{1}{2}[\sin(\alpha+\beta)+\sin(\alpha-\beta)]\\\sin\alpha\cos\beta=-\dfrac{1}{2}[\cos(\alpha+\beta)-\cos(\alpha-\beta)]\\\cos\alpha\cos\beta=\dfrac{1}{2}[\cos(\alpha+\beta)+\cos(\alpha-\beta)]\end{cases}$
```

**Comment by pilgrimlyieu** [comment]
> I think this has to do with the syntax highlighting you're using in the program you are copying the input from, Anki pastes not only the text but the syntax highlighting as well, can you copy the text as it is in anki into a comment here?

Aha, the problem is solved when I copy again from this:)

**Comment by Jwrede** [comment]
Try copying it without a code block in github, github strips the css from the input if it's in a code block

**Comment by pilgrimlyieu** [comment]
Thanks for your help and paticnt!

**Comment by Jwrede** [comment]
Yea if you take the original text where the problem was and then press ctrl+shift+x you'll see there are alot of HTML classes that don't belong there, this is because Anki copies text color or bold text as well

**Comment by pilgrimlyieu** [comment]
![1](https://user-images.githubusercontent.com/80107081/125460417-4c44cd2c-1af3-4de0-bb83-e7d1faa0d062.png)
![2](https://user-images.githubusercontent.com/80107081/125460425-429e39e9-3d70-44d1-8ad8-df560925034c.png)
```markdown
$\begin{cases}\sin\alpha+\sin\beta={{c1::2\sin\dfrac{\alpha+\beta}{2}\cos\dfrac{\alpha-\beta}{2}}}\\\sin\alpha-\sin\beta={{c2::2\cos\dfrac{\alpha+\beta}{2}\sin\dfrac{\alpha-\beta}{2}}}\\\cos\alpha+\cos\beta={{c3::2\cos\dfrac{\alpha+\beta}{2}\cos\dfrac{\alpha-\beta}{2}}}\\\cos\alpha-\cos\beta={{c4::-2\sin\dfrac{\alpha+\beta}{2}\sin\dfrac{\alpha-\beta}{2}}}\end{cases}$
```
New problem!
I am dizzy now.
